CONFIG_GPIO=y
CONFIG_DEBUG_OPTIMIZATIONS=y
CONFIG_SIZE_OPTIMIZATIONS=n
CONFIG_SPEED_OPTIMIZATIONS=n

#CONFIG_SOC_STM32F091XC=y
#CONFIG_BOARD_NUCLEO_F091RC=y
CONFIG_I2C=y
#CONFIG_HAS_DTS=y
CONFIG_SENSOR=y
#CONFIG_HAS_DTS_I2C=y
CONFIG_LIS3MDL=y